title: Zarrish and Fahad
subtitle: are getting married!
email: about@fahadzarrish.wedding
description: >
  Fahad & Zarrish are getting married!
baseurl: ""
url: "http://fahadzarrish.com"
address: |
  Pearl Banquet Hall <br>
  Survey No. 40/1 near <br>
  Army Public School, <br>
  Main Rashid Minhas Road, <br>
  Karachi.
phone: 
email: rsvp<at>fahadzarrish<dot>wedding
social_media:
  twitter: https://twitter.com/hashtag/FahadZarrish
  facebook: https://www.facebook.com/hashtag/FahadZarrish
  instagram: https://www.instagram.com/explore/tags/FahadZarrish
  github: https://github.com/fahadiqbal1/wedding
google_analytics: UA-40896031-8

# SEO Settings
author:
  twitter: soyFahad
twitter:
  username: soyFahad
social:
  name: Fahad & Zarrish's Wedding
  links:
   - https://twitter.com/hashtag/FahadZarrish
   - https://www.facebook.com/hashtag/FahadZarrish
   - https://www.instagram.com/explore/tags/FahadZarrish

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  # - jekyll-assets
  - jekyll-seo-tag
  - jekyll-relative-links
exclude:
  - Gemfile
  - Gemfile.lock
include: ["_pages"]
permalink: /:title/
sass:
    sass_dir: "assets/stylesheets"
    style: compressed

assets:
  compress:
    css: true
    js: true
